repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=100
          - --target-version=py312
        exclude: ^(examples/|docs/|tests/)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args:
          - --line-length=100
          - --target-version=py312
          - --select=E,F,I,B
          - --ignore=E203
          - --fix
          - --unsafe-fixes
        exclude: ^(examples/|docs/|tests/)
